### ISSUE TITLE
大佬 我刚刚入门这个方向，有点问题求帮助

### ISSUE THREAD

**Issue by URRealHero** [ChaofWang/Awesome-Super-Resolution#14]
我在关注Arbitrary-scale super-resolution这方面。 现在的SR是基本都在往这方面做么？ 如果我想做这方面有哪些论文是比较最近比较新而且好的呢。如果能给我一些论文推荐或者现在大方向的指引我将感激不尽

**Comment by ChaofWang** [comment]
1、这个Repo里有以前和最新的SR相对不错的论文，SR问题上需要研究的问题方向有不少，Arbitrary-scale算是一个，你可以自己根据后面的key word或者title去大概看下不同论文的重点是什么；
2、我的认知里最早做arbitrary-scale的是Meta-SR，往后相关的论文在Repo里都有，按关键词找下就好，都是些不错的论文。

**Comment by URRealHero** [comment]
Thx a lot
