### ISSUE TITLE
Could you share Manga109 X2X4X8 data？

### ISSUE THREAD

**Issue by raninbowlalala** [ChaofWang/Awesome-Super-Resolution#3]
Hello！
I want to use Manga109 dataset, but I only find Manga109 original images, could you share X
2X4X8 data to me?  BTW I can't use google dirve.
Thank you!

**Comment by ChaofWang** [comment]
Hello, I don't have this dataset in my laptop. You can try to look at [this](https://pan.baidu.com/s/16R5kPtLyv-pOVzOcb5_aKQ#list/path=%2FAWSRN%2Fdata&parentPath=%2F) code: h39w, but I am not sure if there is this data.
